# Generated by Django 2.1.7 on 2019-07-15 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CyberRATWeb', '0003_search_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='id',
        ),
        migrations.AlterField(
            model_name='search',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
