# Generated by Django 2.1.7 on 2019-07-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberRATWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='linkedin_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
