# Generated by Django 2.1.7 on 2019-07-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberRATWeb', '0004_auto_20190715_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='search',
            name='instagram_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
