# Generated by Django 2.2.3 on 2019-07-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberRATWeb', '0005_auto_20190718_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='facebook_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
