# Generated by Django 2.2.3 on 2019-07-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberRATWeb', '0006_auto_20190729_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='twitter_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
